/// \file persistency/gdml/GramsG4/src/GramsG4PrimaryGeneratorAction.cc
/// \brief Implementation of the GramsG4PrimaryGeneratorAction class
//
// 25-May-2020 WGS: Set some preliminary values for testing GRAMS.
//

#include "GramsG4PrimaryGeneratorAction.hh"

#include "G4Event.hh"
#include "G4GeneralParticleSource.hh"

namespace gramsg4 {

  //....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo......

  PrimaryGeneratorAction::PrimaryGeneratorAction()
    : G4VUserPrimaryGeneratorAction()
    , fParticleSource(0)
  {
    fParticleSource = new G4GeneralParticleSource();
    // Just in case: we only want to generate one particle at a time.
    fParticleSource->SetNumberOfParticles(1);
  }

  //....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo......

  PrimaryGeneratorAction::~PrimaryGeneratorAction()
  {
    delete fParticleSource;
  }

  //....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo......

  void PrimaryGeneratorAction::GeneratePrimaries(G4Event* anEvent)
  {
    // There's nothing to do here; the particles are generated by
    // commands from the Geant4 macro file read by the main program.
    fParticleSource->GeneratePrimaryVertex(anEvent);
  }

} // namespace gramsg4
